name: TFC Apply
on:
  push:
    branches:
      - main
    paths:
      # Replace with your directory, relative to the root of the project
      - 'terraform/**.tf'

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: "tf-demo-api"
  TF_DIRECTORY: "./terraform"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-apply:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.TF_DIRECTORY }}

      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.4
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.4
        # assign id attribute to reference in subsequent steps
        id: apply
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Confirmed from GitHub Actions CI"

      - id: terraform-cloud-check-run-status
        if: ${{ steps.run.outputs.run_status != 'planned_and_finished'}}
        run: |
            echo "Terraform Cloud Run Failed or Requires Further Attention"
            echo "Run Status: '${{ steps.run.outputs.run_status }}'"
            echo "${{ steps.run.outputs.run_link }}"
            exit 1